cloud:
  config:
    fail-fast: true
    retry:
      useRandomPolicy: true
      max-interval: 6000
aggregator:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    topics:
      input: telemetry.sensors.v1
      output: telemetry.snapshots.v1
main:
  allow-bean-definition-overriding: true