spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/smart_home
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    topics:
      snapshots: telemetry.snapshots.v1
      hubs: telemetry.hubs.v1
    consumers:
      snapshots:
        group-id: analyzer-snapshots-group
        client-id: analyzer-snapshots-consumer
        enable-auto-commit: false
      hubs:
        group-id: analyzer-hubs-group
        client-id: analyzer-hubs-consumer
        enable-auto-commit: true

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: WARN